//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalLink.Connect.UserProfileServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", ConfigurationName="UserProfileServiceRef.UserProfileServicePortType")]
    public interface UserProfileServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getSubmitters", ReplyAction="urn:getSubmittersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GlobalLink.Connect.UserProfileServiceRef.getSubmittersResponse getSubmitters(GlobalLink.Connect.UserProfileServiceRef.getSubmittersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getSubmitters", ReplyAction="urn:getSubmittersResponse")]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.getSubmittersResponse> getSubmittersAsync(GlobalLink.Connect.UserProfileServiceRef.getSubmittersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:createUser", ReplyAction="urn:createUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GlobalLink.Connect.UserProfileServiceRef.createUserResponse createUser(GlobalLink.Connect.UserProfileServiceRef.createUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:createUser", ReplyAction="urn:createUserResponse")]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.createUserResponse> createUserAsync(GlobalLink.Connect.UserProfileServiceRef.createUserRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:findByTicket", ReplyAction="urn:findByTicketResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GlobalLink.Connect.UserProfileServiceRef.findByTicketResponse findByTicket(GlobalLink.Connect.UserProfileServiceRef.findByTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:findByTicket", ReplyAction="urn:findByTicketResponse")]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.findByTicketResponse> findByTicketAsync(GlobalLink.Connect.UserProfileServiceRef.findByTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getUserLanguages", ReplyAction="urn:getUserLanguagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesResponse getUserLanguages(GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getUserLanguages", ReplyAction="urn:getUserLanguagesResponse")]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesResponse> getUserLanguagesAsync(GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesRequest request);
        
        // CODEGEN: Generating message contract since the operation getCurrentUserLanguages is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCurrentUserLanguages", ReplyAction="urn:getCurrentUserLanguagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesResponse getCurrentUserLanguages(GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCurrentUserLanguages", ReplyAction="urn:getCurrentUserLanguagesResponse")]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesResponse> getCurrentUserLanguagesAsync(GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class UserProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> availableTasksField;
        
        private string organizationNameField;
        
        private Role[] systemRolesField;
        
        private Task[] tasksField;
        
        private string ticketField;
        
        private UserInfo userInfoField;
        
        private string vendorNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> availableTasks {
            get {
                return this.availableTasksField;
            }
            set {
                this.availableTasksField = value;
                this.RaisePropertyChanged("availableTasks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string organizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
                this.RaisePropertyChanged("organizationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("systemRoles", IsNullable=true, Order=2)]
        public Role[] systemRoles {
            get {
                return this.systemRolesField;
            }
            set {
                this.systemRolesField = value;
                this.RaisePropertyChanged("systemRoles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tasks", IsNullable=true, Order=3)]
        public Task[] tasks {
            get {
                return this.tasksField;
            }
            set {
                this.tasksField = value;
                this.RaisePropertyChanged("tasks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public UserInfo userInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
                this.RaisePropertyChanged("userInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string vendorName {
            get {
                return this.vendorNameField;
            }
            set {
                this.vendorNameField = value;
                this.RaisePropertyChanged("vendorName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class Role : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Policy[] policiesField;
        
        private string roleIdField;
        
        private RoleTypeEnum roleTypeField;
        
        private Task[] tasksField;
        
        private string ticketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("policies", IsNullable=true, Order=0)]
        public Policy[] policies {
            get {
                return this.policiesField;
            }
            set {
                this.policiesField = value;
                this.RaisePropertyChanged("policies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string roleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("roleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public RoleTypeEnum roleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
                this.RaisePropertyChanged("roleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tasks", IsNullable=true, Order=3)]
        public Task[] tasks {
            get {
                return this.tasksField;
            }
            set {
                this.tasksField = value;
                this.RaisePropertyChanged("tasks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class Policy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string categoryField;
        
        private string policyIdField;
        
        private RoleTypeEnum policyTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string policyId {
            get {
                return this.policyIdField;
            }
            set {
                this.policyIdField = value;
                this.RaisePropertyChanged("policyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public RoleTypeEnum policyType {
            get {
                return this.policyTypeField;
            }
            set {
                this.policyTypeField = value;
                this.RaisePropertyChanged("policyType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class RoleTypeEnum : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class Language : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string localeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
                this.RaisePropertyChanged("locale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class LanguageDirection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Language sourceLanguageField;
        
        private Language targetLanguageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Language sourceLanguage {
            get {
                return this.sourceLanguageField;
            }
            set {
                this.sourceLanguageField = value;
                this.RaisePropertyChanged("sourceLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Language targetLanguage {
            get {
                return this.targetLanguageField;
            }
            set {
                this.targetLanguageField = value;
                this.RaisePropertyChanged("targetLanguage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class TiUserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LanguageDirection[] languageDirectionsField;
        
        private System.Nullable<long> organizationIdField;
        
        private string[] projectRolesField;
        
        private string[] projectTicketField;
        
        private string[] systemRolesField;
        
        private System.Nullable<long> vendorIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("languageDirections", IsNullable=true, Order=0)]
        public LanguageDirection[] languageDirections {
            get {
                return this.languageDirectionsField;
            }
            set {
                this.languageDirectionsField = value;
                this.RaisePropertyChanged("languageDirections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> organizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
                this.RaisePropertyChanged("organizationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("projectRoles", IsNullable=true, Order=2)]
        public string[] projectRoles {
            get {
                return this.projectRolesField;
            }
            set {
                this.projectRolesField = value;
                this.RaisePropertyChanged("projectRoles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("projectTicket", IsNullable=true, Order=3)]
        public string[] projectTicket {
            get {
                return this.projectTicketField;
            }
            set {
                this.projectTicketField = value;
                this.RaisePropertyChanged("projectTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("systemRoles", IsNullable=true, Order=4)]
        public string[] systemRoles {
            get {
                return this.systemRolesField;
            }
            set {
                this.systemRolesField = value;
                this.RaisePropertyChanged("systemRoles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> vendorId {
            get {
                return this.vendorIdField;
            }
            set {
                this.vendorIdField = value;
                this.RaisePropertyChanged("vendorId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> accountNonExpiredField;
        
        private System.Nullable<bool> accountLockedField;
        
        private string addressField;
        
        private System.Nullable<bool> autoClaimMultipleTasksField;
        
        private System.Nullable<bool> claimMultipleJobTasksField;
        
        private System.Nullable<bool> credentialsNonExpiredField;
        
        private string dateLastLoginField;
        
        private string departmentField;
        
        private string emailAddressField;
        
        private System.Nullable<bool> emailNotificationField;
        
        private System.Nullable<bool> enabledField;
        
        private string faxField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string passwordField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string timeZoneField;
        
        private string userNameField;
        
        private string userTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> accountLocked {
            get {
                return this.accountLockedField;
            }
            set {
                this.accountLockedField = value;
                this.RaisePropertyChanged("accountLocked");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> accountNonExpired {
            get {
                return this.accountNonExpiredField;
            }
            set {
                this.accountNonExpiredField = value;
                this.RaisePropertyChanged("accountNonExpired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<bool> autoClaimMultipleTasks {
            get {
                return this.autoClaimMultipleTasksField;
            }
            set {
                this.autoClaimMultipleTasksField = value;
                this.RaisePropertyChanged("autoClaimMultipleTasks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> claimMultipleJobTasks {
            get {
                return this.claimMultipleJobTasksField;
            }
            set {
                this.claimMultipleJobTasksField = value;
                this.RaisePropertyChanged("claimMultipleJobTasks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<bool> credentialsNonExpired {
            get {
                return this.credentialsNonExpiredField;
            }
            set {
                this.credentialsNonExpiredField = value;
                this.RaisePropertyChanged("credentialsNonExpired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string dateLastLogin {
            get {
                return this.dateLastLoginField;
            }
            set {
                this.dateLastLoginField = value;
                this.RaisePropertyChanged("dateLastLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> emailNotification {
            get {
                return this.emailNotificationField;
            }
            set {
                this.emailNotificationField = value;
                this.RaisePropertyChanged("emailNotification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<bool> enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
                this.RaisePropertyChanged("phone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
                this.RaisePropertyChanged("phone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("timeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string userType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
                this.RaisePropertyChanged("userType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class Task : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string groupNameField;
        
        private System.Nullable<int> selectStyleField;
        
        private System.Nullable<long> taskIdField;
        
        private string taskNameField;
        
        private System.Nullable<int> weightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> selectStyle {
            get {
                return this.selectStyleField;
            }
            set {
                this.selectStyleField = value;
                this.RaisePropertyChanged("selectStyle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
                this.RaisePropertyChanged("taskId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string taskName {
            get {
                return this.taskNameField;
            }
            set {
                this.taskNameField = value;
                this.RaisePropertyChanged("taskName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubmitters", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class getSubmittersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        public string projectShortCode;
        
        public getSubmittersRequest() {
        }
        
        public getSubmittersRequest(string projectShortCode) {
            this.projectShortCode = projectShortCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSubmittersResponse", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class getSubmittersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public GlobalLink.Connect.UserProfileServiceRef.UserProfile[] @return;
        
        public getSubmittersResponse() {
        }
        
        public getSubmittersResponse(GlobalLink.Connect.UserProfileServiceRef.UserProfile[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUser", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class createUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        public GlobalLink.Connect.UserProfileServiceRef.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=1)]
        public GlobalLink.Connect.UserProfileServiceRef.TiUserInfo tiUserInfo;
        
        public createUserRequest() {
        }
        
        public createUserRequest(GlobalLink.Connect.UserProfileServiceRef.UserInfo userInfo, GlobalLink.Connect.UserProfileServiceRef.TiUserInfo tiUserInfo) {
            this.userInfo = userInfo;
            this.tiUserInfo = tiUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUserResponse", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class createUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string[] @return;
        
        public createUserResponse() {
        }
        
        public createUserResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByTicket", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class findByTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        public string ticket;
        
        public findByTicketRequest() {
        }
        
        public findByTicketRequest(string ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByTicketResponse", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class findByTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GlobalLink.Connect.UserProfileServiceRef.UserProfile @return;
        
        public findByTicketResponse() {
        }
        
        public findByTicketResponse(GlobalLink.Connect.UserProfileServiceRef.UserProfile @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserLanguages", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class getUserLanguagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        public string userTicket;
        
        public getUserLanguagesRequest() {
        }
        
        public getUserLanguagesRequest(string userTicket) {
            this.userTicket = userTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserLanguagesResponse", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class getUserLanguagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public GlobalLink.Connect.UserProfileServiceRef.Language[] @return;
        
        public getUserLanguagesResponse() {
        }
        
        public getUserLanguagesResponse(GlobalLink.Connect.UserProfileServiceRef.Language[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCurrentUserLanguagesRequest {
        
        public getCurrentUserLanguagesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentUserLanguagesResponse", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class getCurrentUserLanguagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public GlobalLink.Connect.UserProfileServiceRef.Language[] @return;
        
        public getCurrentUserLanguagesResponse() {
        }
        
        public getCurrentUserLanguagesResponse(GlobalLink.Connect.UserProfileServiceRef.Language[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserProfileServicePortTypeChannel : GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfileServicePortTypeClient : System.ServiceModel.ClientBase<GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType>, GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType {
        
        public UserProfileServicePortTypeClient() {
        }
        
        public UserProfileServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalLink.Connect.UserProfileServiceRef.getSubmittersResponse GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.getSubmitters(GlobalLink.Connect.UserProfileServiceRef.getSubmittersRequest request) {
            return base.Channel.getSubmitters(request);
        }
        
        public GlobalLink.Connect.UserProfileServiceRef.UserProfile[] getSubmitters(string projectShortCode) {
            GlobalLink.Connect.UserProfileServiceRef.getSubmittersRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.getSubmittersRequest();
            inValue.projectShortCode = projectShortCode;
            GlobalLink.Connect.UserProfileServiceRef.getSubmittersResponse retVal = ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).getSubmitters(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.getSubmittersResponse> GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.getSubmittersAsync(GlobalLink.Connect.UserProfileServiceRef.getSubmittersRequest request) {
            return base.Channel.getSubmittersAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.getSubmittersResponse> getSubmittersAsync(string projectShortCode) {
            GlobalLink.Connect.UserProfileServiceRef.getSubmittersRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.getSubmittersRequest();
            inValue.projectShortCode = projectShortCode;
            return ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).getSubmittersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalLink.Connect.UserProfileServiceRef.createUserResponse GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.createUser(GlobalLink.Connect.UserProfileServiceRef.createUserRequest request) {
            return base.Channel.createUser(request);
        }
        
        public string[] createUser(GlobalLink.Connect.UserProfileServiceRef.UserInfo userInfo, GlobalLink.Connect.UserProfileServiceRef.TiUserInfo tiUserInfo) {
            GlobalLink.Connect.UserProfileServiceRef.createUserRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.createUserRequest();
            inValue.userInfo = userInfo;
            inValue.tiUserInfo = tiUserInfo;
            GlobalLink.Connect.UserProfileServiceRef.createUserResponse retVal = ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).createUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.createUserResponse> GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.createUserAsync(GlobalLink.Connect.UserProfileServiceRef.createUserRequest request) {
            return base.Channel.createUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.createUserResponse> createUserAsync(GlobalLink.Connect.UserProfileServiceRef.UserInfo userInfo, GlobalLink.Connect.UserProfileServiceRef.TiUserInfo tiUserInfo) {
            GlobalLink.Connect.UserProfileServiceRef.createUserRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.createUserRequest();
            inValue.userInfo = userInfo;
            inValue.tiUserInfo = tiUserInfo;
            return ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).createUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalLink.Connect.UserProfileServiceRef.findByTicketResponse GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.findByTicket(GlobalLink.Connect.UserProfileServiceRef.findByTicketRequest request) {
            return base.Channel.findByTicket(request);
        }
        
        public GlobalLink.Connect.UserProfileServiceRef.UserProfile findByTicket(string ticket) {
            GlobalLink.Connect.UserProfileServiceRef.findByTicketRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.findByTicketRequest();
            inValue.ticket = ticket;
            GlobalLink.Connect.UserProfileServiceRef.findByTicketResponse retVal = ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).findByTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.findByTicketResponse> GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.findByTicketAsync(GlobalLink.Connect.UserProfileServiceRef.findByTicketRequest request) {
            return base.Channel.findByTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.findByTicketResponse> findByTicketAsync(string ticket) {
            GlobalLink.Connect.UserProfileServiceRef.findByTicketRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.findByTicketRequest();
            inValue.ticket = ticket;
            return ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).findByTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesResponse GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.getUserLanguages(GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesRequest request) {
            return base.Channel.getUserLanguages(request);
        }
        
        public GlobalLink.Connect.UserProfileServiceRef.Language[] getUserLanguages(string userTicket) {
            GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesRequest();
            inValue.userTicket = userTicket;
            GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesResponse retVal = ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).getUserLanguages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesResponse> GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.getUserLanguagesAsync(GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesRequest request) {
            return base.Channel.getUserLanguagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesResponse> getUserLanguagesAsync(string userTicket) {
            GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.getUserLanguagesRequest();
            inValue.userTicket = userTicket;
            return ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).getUserLanguagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesResponse GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.getCurrentUserLanguages(GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesRequest request) {
            return base.Channel.getCurrentUserLanguages(request);
        }
        
        public GlobalLink.Connect.UserProfileServiceRef.Language[] getCurrentUserLanguages() {
            GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesRequest();
            GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesResponse retVal = ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).getCurrentUserLanguages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesResponse> GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType.getCurrentUserLanguagesAsync(GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesRequest request) {
            return base.Channel.getCurrentUserLanguagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesResponse> getCurrentUserLanguagesAsync() {
            GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesRequest inValue = new GlobalLink.Connect.UserProfileServiceRef.getCurrentUserLanguagesRequest();
            return ((GlobalLink.Connect.UserProfileServiceRef.UserProfileServicePortType)(this)).getCurrentUserLanguagesAsync(inValue);
        }
    }
}
