//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalLink.Connect.ProjectServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", ConfigurationName="ProjectServiceRef.ProjectServicePortType")]
    public interface ProjectServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:findByTicket", ReplyAction="urn:findByTicketResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GlobalLink.Connect.ProjectServiceRef.findByTicketResponse findByTicket(GlobalLink.Connect.ProjectServiceRef.findByTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:findProjectByName", ReplyAction="urn:findProjectByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GlobalLink.Connect.ProjectServiceRef.findProjectByNameResponse findProjectByName(GlobalLink.Connect.ProjectServiceRef.findProjectByNameRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:findProjectByShortCode", ReplyAction="urn:findProjectByShortCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GlobalLink.Connect.ProjectServiceRef.findProjectByShortCodeResponse findProjectByShortCode(GlobalLink.Connect.ProjectServiceRef.findProjectByShortCodeRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getUserProjectsRequest", ReplyAction="urn:getUserProjectsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GlobalLink.Connect.ProjectServiceRef.getUserProjectsResponse getUserProjects(GlobalLink.Connect.ProjectServiceRef.getUserProjectsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class Project : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Announcement[] announcementsField;
        
        private ContentMonitorPluginInfo contentMonitorPluginInfoField;
        
        private WorkflowDefinition defaultTargetWorkflowDefinitionField;
        
        private string defaultTargetWorkflowDefinitionTicketField;
        
        private FileFormatProfile[] fileFormatProfilesField;
        
        private System.Nullable<bool>[] includeSubmissionNameInLocalizationKitField;
        
        private Metadata[] metadataField;
        
        private string organizationNameField;
        
        private ProjectCustomFieldConfiguration[] projectCustomFieldConfigurationField;
        
        private ProjectInfo projectInfoField;
        
        private ProjectLanguageDirection[] projectLanguageDirectionsField;
        
        private string ticketField;
        
        private WorkflowDefinition[] workflowDefinitionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("announcements", IsNullable=true, Order=0)]
        public Announcement[] announcements {
            get {
                return this.announcementsField;
            }
            set {
                this.announcementsField = value;
                this.RaisePropertyChanged("announcements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public ContentMonitorPluginInfo contentMonitorPluginInfo {
            get {
                return this.contentMonitorPluginInfoField;
            }
            set {
                this.contentMonitorPluginInfoField = value;
                this.RaisePropertyChanged("contentMonitorPluginInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public WorkflowDefinition defaultTargetWorkflowDefinition {
            get {
                return this.defaultTargetWorkflowDefinitionField;
            }
            set {
                this.defaultTargetWorkflowDefinitionField = value;
                this.RaisePropertyChanged("defaultTargetWorkflowDefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string defaultTargetWorkflowDefinitionTicket {
            get {
                return this.defaultTargetWorkflowDefinitionTicketField;
            }
            set {
                this.defaultTargetWorkflowDefinitionTicketField = value;
                this.RaisePropertyChanged("defaultTargetWorkflowDefinitionTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileFormatProfiles", IsNullable=true, Order=4)]
        public FileFormatProfile[] fileFormatProfiles {
            get {
                return this.fileFormatProfilesField;
            }
            set {
                this.fileFormatProfilesField = value;
                this.RaisePropertyChanged("fileFormatProfiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("includeSubmissionNameInLocalizationKit", IsNullable=true, Order=5)]
        public System.Nullable<bool>[] includeSubmissionNameInLocalizationKit {
            get {
                return this.includeSubmissionNameInLocalizationKitField;
            }
            set {
                this.includeSubmissionNameInLocalizationKitField = value;
                this.RaisePropertyChanged("includeSubmissionNameInLocalizationKit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadata", IsNullable=true, Order=6)]
        public Metadata[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string organizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
                this.RaisePropertyChanged("organizationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("projectCustomFieldConfiguration", IsNullable=true, Order=8)]
        public ProjectCustomFieldConfiguration[] projectCustomFieldConfiguration {
            get {
                return this.projectCustomFieldConfigurationField;
            }
            set {
                this.projectCustomFieldConfigurationField = value;
                this.RaisePropertyChanged("projectCustomFieldConfiguration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public ProjectInfo projectInfo {
            get {
                return this.projectInfoField;
            }
            set {
                this.projectInfoField = value;
                this.RaisePropertyChanged("projectInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("projectLanguageDirections", IsNullable=true, Order=10)]
        public ProjectLanguageDirection[] projectLanguageDirections {
            get {
                return this.projectLanguageDirectionsField;
            }
            set {
                this.projectLanguageDirectionsField = value;
                this.RaisePropertyChanged("projectLanguageDirections");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("workflowDefinitions", IsNullable=true, Order=12)]
        public WorkflowDefinition[] workflowDefinitions {
            get {
                return this.workflowDefinitionsField;
            }
            set {
                this.workflowDefinitionsField = value;
                this.RaisePropertyChanged("workflowDefinitions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class Announcement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string announcementTextField;
        
        private Date dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string announcementText {
            get {
                return this.announcementTextField;
            }
            set {
                this.announcementTextField = value;
                this.RaisePropertyChanged("announcementText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Date date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class Date : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool criticalField;
        
        private long dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool critical {
            get {
                return this.criticalField;
            }
            set {
                this.criticalField = value;
                this.RaisePropertyChanged("critical");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class Language : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string localeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
                this.RaisePropertyChanged("locale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class ProjectLanguageDirection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Language sourceLanguageField;
        
        private Language targetLanguageField;
        
        private System.Nullable<bool> defaultField;
        
        private System.Nullable<bool> frequentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Language sourceLanguage {
            get {
                return this.sourceLanguageField;
            }
            set {
                this.sourceLanguageField = value;
                this.RaisePropertyChanged("sourceLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Language targetLanguage {
            get {
                return this.targetLanguageField;
            }
            set {
                this.targetLanguageField = value;
                this.RaisePropertyChanged("targetLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<bool> @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
                this.RaisePropertyChanged("default");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<bool> frequent {
            get {
                return this.frequentField;
            }
            set {
                this.frequentField = value;
                this.RaisePropertyChanged("frequent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class ProjectInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIdentifierField;
        
        private string defaultJobWorkflowDefinitionTicketField;
        
        private string defaultSubmissionWorkflowDefinitionTicketField;
        
        private string defaultTargetWorkflowDefinitionTicketField;
        
        private System.Nullable<bool> enabledField;
        
        private string nameField;
        
        private string shortCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string clientIdentifier {
            get {
                return this.clientIdentifierField;
            }
            set {
                this.clientIdentifierField = value;
                this.RaisePropertyChanged("clientIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string defaultJobWorkflowDefinitionTicket {
            get {
                return this.defaultJobWorkflowDefinitionTicketField;
            }
            set {
                this.defaultJobWorkflowDefinitionTicketField = value;
                this.RaisePropertyChanged("defaultJobWorkflowDefinitionTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string defaultSubmissionWorkflowDefinitionTicket {
            get {
                return this.defaultSubmissionWorkflowDefinitionTicketField;
            }
            set {
                this.defaultSubmissionWorkflowDefinitionTicketField = value;
                this.RaisePropertyChanged("defaultSubmissionWorkflowDefinitionTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string defaultTargetWorkflowDefinitionTicket {
            get {
                return this.defaultTargetWorkflowDefinitionTicketField;
            }
            set {
                this.defaultTargetWorkflowDefinitionTicketField = value;
                this.RaisePropertyChanged("defaultTargetWorkflowDefinitionTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string shortCode {
            get {
                return this.shortCodeField;
            }
            set {
                this.shortCodeField = value;
                this.RaisePropertyChanged("shortCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class ProjectCustomFieldConfiguration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> mandatoryField;
        
        private string nameField;
        
        private string typeField;
        
        private string valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
                this.RaisePropertyChanged("mandatory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class Metadata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class FileFormatProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> configurableField;
        
        private System.Nullable<bool> isDefaultField;
        
        private string mimeTypeField;
        
        private string pluginIdField;
        
        private string pluginNameField;
        
        private string profileNameField;
        
        private WorkflowDefinition targetWorkflowDefinitionField;
        
        private string ticketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> configurable {
            get {
                return this.configurableField;
            }
            set {
                this.configurableField = value;
                this.RaisePropertyChanged("configurable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> isDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
                this.RaisePropertyChanged("isDefault");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string pluginId {
            get {
                return this.pluginIdField;
            }
            set {
                this.pluginIdField = value;
                this.RaisePropertyChanged("pluginId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string pluginName {
            get {
                return this.pluginNameField;
            }
            set {
                this.pluginNameField = value;
                this.RaisePropertyChanged("pluginName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string profileName {
            get {
                return this.profileNameField;
            }
            set {
                this.profileNameField = value;
                this.RaisePropertyChanged("profileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public WorkflowDefinition targetWorkflowDefinition {
            get {
                return this.targetWorkflowDefinitionField;
            }
            set {
                this.targetWorkflowDefinitionField = value;
                this.RaisePropertyChanged("targetWorkflowDefinition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class WorkflowDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string nameField;
        
        private string ticketField;
        
        private EntityTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public EntityTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class EntityTypeEnum : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.model.projectdirector.gs4tr.org/xsd")]
    public partial class ContentMonitorPluginInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pluginIdField;
        
        private string pluginNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string pluginId {
            get {
                return this.pluginIdField;
            }
            set {
                this.pluginIdField = value;
                this.RaisePropertyChanged("pluginId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string pluginName {
            get {
                return this.pluginNameField;
            }
            set {
                this.pluginNameField = value;
                this.RaisePropertyChanged("pluginName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByTicket", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class findByTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        public string ticket;
        
        public findByTicketRequest() {
        }
        
        public findByTicketRequest(string ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByTicketResponse", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class findByTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GlobalLink.Connect.ProjectServiceRef.Project @return;
        
        public findByTicketResponse() {
        }
        
        public findByTicketResponse(GlobalLink.Connect.ProjectServiceRef.Project @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProjectByName", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class findProjectByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        public string projectName;
        
        public findProjectByNameRequest() {
        }
        
        public findProjectByNameRequest(string projectName) {
            this.projectName = projectName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProjectByNameResponse", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class findProjectByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GlobalLink.Connect.ProjectServiceRef.Project @return;
        
        public findProjectByNameResponse() {
        }
        
        public findProjectByNameResponse(GlobalLink.Connect.ProjectServiceRef.Project @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProjectByShortCode", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class findProjectByShortCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        public string projectShortCode;
        
        public findProjectByShortCodeRequest() {
        }
        
        public findProjectByShortCodeRequest(string projectShortCode) {
            this.projectShortCode = projectShortCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findProjectByShortCodeResponse", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class findProjectByShortCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GlobalLink.Connect.ProjectServiceRef.Project @return;
        
        public findProjectByShortCodeResponse() {
        }
        
        public findProjectByShortCodeResponse(GlobalLink.Connect.ProjectServiceRef.Project @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserProjects", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class getUserProjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        public bool isSubProjectIncluded;
        
        public getUserProjectsRequest() {
        }
        
        public getUserProjectsRequest(bool isSubProjectIncluded) {
            this.isSubProjectIncluded = isSubProjectIncluded;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserProjectsResponse", WrapperNamespace="http://impl.services.service.ws.projectdirector.gs4tr.org", IsWrapped=true)]
    public partial class getUserProjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://impl.services.service.ws.projectdirector.gs4tr.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public GlobalLink.Connect.ProjectServiceRef.Project[] @return;
        
        public getUserProjectsResponse() {
        }
        
        public getUserProjectsResponse(GlobalLink.Connect.ProjectServiceRef.Project[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProjectServicePortTypeChannel : GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectServicePortTypeClient : System.ServiceModel.ClientBase<GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType>, GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType {
        
        public ProjectServicePortTypeClient() {
        }
        
        public ProjectServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalLink.Connect.ProjectServiceRef.findByTicketResponse GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType.findByTicket(GlobalLink.Connect.ProjectServiceRef.findByTicketRequest request) {
            return base.Channel.findByTicket(request);
        }
        
        public GlobalLink.Connect.ProjectServiceRef.Project findByTicket(string ticket) {
            GlobalLink.Connect.ProjectServiceRef.findByTicketRequest inValue = new GlobalLink.Connect.ProjectServiceRef.findByTicketRequest();
            inValue.ticket = ticket;
            GlobalLink.Connect.ProjectServiceRef.findByTicketResponse retVal = ((GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType)(this)).findByTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalLink.Connect.ProjectServiceRef.findProjectByNameResponse GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType.findProjectByName(GlobalLink.Connect.ProjectServiceRef.findProjectByNameRequest request) {
            return base.Channel.findProjectByName(request);
        }
        
        public GlobalLink.Connect.ProjectServiceRef.Project findProjectByName(string projectName) {
            GlobalLink.Connect.ProjectServiceRef.findProjectByNameRequest inValue = new GlobalLink.Connect.ProjectServiceRef.findProjectByNameRequest();
            inValue.projectName = projectName;
            GlobalLink.Connect.ProjectServiceRef.findProjectByNameResponse retVal = ((GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType)(this)).findProjectByName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalLink.Connect.ProjectServiceRef.findProjectByShortCodeResponse GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType.findProjectByShortCode(GlobalLink.Connect.ProjectServiceRef.findProjectByShortCodeRequest request) {
            return base.Channel.findProjectByShortCode(request);
        }
        
        public GlobalLink.Connect.ProjectServiceRef.Project findProjectByShortCode(string projectShortCode) {
            GlobalLink.Connect.ProjectServiceRef.findProjectByShortCodeRequest inValue = new GlobalLink.Connect.ProjectServiceRef.findProjectByShortCodeRequest();
            inValue.projectShortCode = projectShortCode;
            GlobalLink.Connect.ProjectServiceRef.findProjectByShortCodeResponse retVal = ((GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType)(this)).findProjectByShortCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GlobalLink.Connect.ProjectServiceRef.getUserProjectsResponse GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType.getUserProjects(GlobalLink.Connect.ProjectServiceRef.getUserProjectsRequest request) {
            return base.Channel.getUserProjects(request);
        }
        
        public GlobalLink.Connect.ProjectServiceRef.Project[] getUserProjects(bool isSubProjectIncluded) {
            GlobalLink.Connect.ProjectServiceRef.getUserProjectsRequest inValue = new GlobalLink.Connect.ProjectServiceRef.getUserProjectsRequest();
            inValue.isSubProjectIncluded = isSubProjectIncluded;
            GlobalLink.Connect.ProjectServiceRef.getUserProjectsResponse retVal = ((GlobalLink.Connect.ProjectServiceRef.ProjectServicePortType)(this)).getUserProjects(inValue);
            return retVal.@return;
        }
    }
}
